### ISSUE TITLE
Error while trying to get token after v0.6 update

### ISSUE THREAD

**Issue by rina-spinne** [netauth/netauth#15]
After the v0.6.0 update on the server, when trying to get a token from any entity the server fails with the error

```
netauthd.rpc2: Error Issuing Token: entity=rina capabilities=[] service=netauth error="a required key is not available"
```

Rolling back to v0.5.0 fixes the issue. Client is on v0.6.0 and most configurations are the same as the ones on the docs.

**Comment by the-maldridge** [comment]
The key filenames were made more generic in 0.6 to support future key-loading mechanisms such as DNS TXT records.  Rename your keys to be rsa-public.tokenkey and rsa-private.tokenkey and it will work.

Yes, this should be documented, I'll add it to the release patch notes.
